name: Webhook Callback

on:
  repository_dispatch:
    types: webhookCallbackDynamic

  jobs:
    respond:
      name: Calls the callback being passed in
      runs-on: ubuntu-18.04
      steps:
        - name: callCallback
          id: callCallback
          uses: fjogeleit/http-request-action@master
          with:
            url: ${{ github.event.client_payload.callbackUri }}
            method: 'POST'
            customHeaders: '{ "Content-Type": "application/json" }'
            data: '{ "success": ${{ github.event.client_payload.success }}, "mdMessage": ${{ github.event.client_payload.mdMessage }} }'
        - name: show http response
          run: echo ${{ steps.callCallback.outputs.response }}