name: Webhook Callback Failure

on:
  repository_dispatch:
    types: webhookCallbackFailure

jobs:
  respond:
    name: Calls the callback being passed in
    runs-on: ubuntu-18.04
    steps:
      - name: getToken
        id: getToken
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://auth.staging.cloud.armory.io/oauth/token"
          method: "POST"
          customHeaders: '{ "Content-Type": "application/x-www-form-urlencoded" }'
          data: 'audience=https://api.staging.cloud.armory.io&grant_type=client_credentials&client_id=${{ secrets.ARMORY_STAGING_CLIENT_ID }}&client_secret=${{ secrets.ARMORY_STAGING_CLIENT_SECRET }}'
      - name: callCallback
        id: callCallback
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ github.event.client_payload.callbackUri }}
          method: 'POST'
          bearerToken: ${{ fromJSON(steps.getToken.outputs.response).access_token }}
          customHeaders: '{ "Content-Type": "application/json" }'
          data: '{ "success": false, "mdMessage": "Webhook was NOT successful." }'
      - name: show http response
        run: echo ${{ steps.callCallback.outputs.response }}
